version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
        environment:
          TZ: Asia/Tokyo


commands:
  restore_npm:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-v1-{{ checksum "package-lock.json" }}
  save_npm:
    steps:
      - save_cache:
          name: Cache npm dependencies
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/repo/node_modules

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Install npm dependencies
          command: npm ci
      - save_npm
  lint:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Run lint
          command: npm run lint
  
  deploy:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: generate statics
          command: npm run generate
      - run:
          name: deploy
          command: ./node_modules/.bin/firebase deploy --token=$FIREBAASE_TOKEN

workflows:
  deploy:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - generate:
          requires:
            - lint
          filters:
            branches:
              only: master


