version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
        environment:
          TZ: Asia/Tokyo


commands:
  restore_npm:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-v1-{{ checksum "package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
  save_npm:
    steps:
      - save_cache:
          name: Cache npm dependencies
          key: npm-v1-{{ checksum "package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
          paths:
            - ~/repo/node_modules
            - ~/repo/functions/node_modules

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Install npm dependencies
          command: npm ci
      - run:
          name: Install npm
          command: cd functions && npm install
      - run:
          name: install firebase-tools
          command: npm install -D firebase-tools
      - save_npm
  lint:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Run lint
          command: npm run lint

  host_deploy:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: generate statics
          command: npm run generate
      - run:
          name: deploy
          command: ./node_modules/.bin/firebase deploy --only hosting --token=$FIREBASE_TOKEN

  function_deploy:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: deploy
          command: ./functions/node_modules/.bin/firebase deploy --only functions --token=$FIREBASE_TOKEN

workflows:
  hosting-deploy:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - host_deploy:
          requires:
            - lint
          # filters:
          #   branches:
          #     only: master

  function-deploy:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - function_deploy:
          requires:
            - lint
